### ISSUE TITLE
Build and run docs locally?

### ISSUE THREAD

**Issue by harperjohn** [QuestPDF/QuestPDF-Documentation#12]
I work in an "air gapped" environment, and would like to be able to run/host the docs locally.

The readme does not seem to mention how to build the docs (just looked quickly).

Please point me to the building/hosting instructions or please give me a brief explanation of the process.

Thanks!!! :)

**Comment by MarcinZiabek** [comment]
Documentation is written using the Vuepress library. The deployment process can be found in its official documentation. It is very easy 😁
