### ISSUE TITLE
Instructions/Documentation for Blazor/WASM

### ISSUE THREAD

**Issue by TorreyGarland** [QuestPDF/QuestPDF-Documentation#19]
The link for the example at https://github.com/pablopioli/Blazor-QuestPDF is deader than dillinger.

**Comment by MarcinZiabek** [comment]
I am not aware about this repository. It is not a part of officially supported documentation 😅

**Comment by TorreyGarland** [comment]
Found the link here:  https://github.com/QuestPDF/QuestPDF-Documentation/pull/7

Are there any samples or documentation for how to use this with Blazor?

**Comment by MarcinZiabek** [comment]
@pablopioli Would you like to take a look, please? 😁

**Comment by pablopioli** [comment]
@TorreyGarland If you look in the pull request you see mentioned a sample. Take a look at
https://github.com/pablopioli/Blazor-QuestPDF

**Comment by MarcinZiabek** [comment]
I am getting the 404 when opening https://github.com/pablopioli/Blazor-QuestPDF. Maybe something wrong with repository access settings?

![image](https://user-images.githubusercontent.com/9263853/168429616-5db74a77-a3e2-4b82-850f-acb21c4b67fb.png)

**Comment by pablopioli** [comment]
Sorry, one day I was doing cleanup of a lot of old samples and changed it's visibilty.

It's public now.

**Comment by TorreyGarland** [comment]
Thanks for restoring this.
