### ISSUE TITLE
Getting virus detected on downloaded documentation

### ISSUE THREAD

**Issue by David-H-Bolton** [QuestPDF/QuestPDF-Documentation#21]
This is on Windows 11. It says it's severe and is Trojan:Script/Wacatac.B!ml, I get this warning any time I download the file QuestPDF-Documentation-main.zip. It gets zapped. I'll download files using Git instead and see if it still occurs.

**Comment by MarcinZiabek** [comment]
I have downloaded the code base as a ZIP file. Then performed a scan using Microsoft Defender on Windows 11. No threats were found. Closing 😁
