### ISSUE TITLE
Broken link to getting started

### ISSUE THREAD

**Issue by jawn** [QuestPDF/QuestPDF-Documentation#31]
Go to https://www.questpdf.com/quick-start

The following link gives a 404 at links to .html
`Read <a href="[/getting-started.html](https://www.questpdf.com/getting-started.html)">the Getting started tutorial</a> to learn
`

**Comment by MarcinZiabek** [comment]
Thank you for noticing this issue. The problem was related to `pretty links` in vitepress and the way how DigitalOcean hosts static websites. Fixed  😁
