### ISSUE TITLE
404 error "sticks"

### ISSUE THREAD

**Issue by girlpunk** [QuestPDF/QuestPDF-Documentation#34]
After visiting a page that does not exist and recieving a 404 error, navigating to another page shows the content below but does not remove the error:

![image](https://user-images.githubusercontent.com/161093/234578117-ac43105c-0e81-4305-9d76-f8d814e63b4f.png)

**Comment by MarcinZiabek** [comment]
This particular problem was related to Vitepress issues and has already been resolved. This library has really matured a lot! 

Closing 😀
