### ISSUE TITLE
Why Process.Start() twice?

### ISSUE THREAD

**Issue by RohimChou** [QuestPDF/QuestPDF-Documentation#6]
New to PDF processing and found this magnificent library! When read through the getting started section, notice that in the document generation section's sample code `Process.Start()` are called twice. Just out of curiosity, is there any reason behind this?

![image](https://user-images.githubusercontent.com/21984361/143770513-7c94036d-e73e-4fbb-ad0b-d15f3ac3eb00.png)

**Comment by MarcinZiabek** [comment]
Thank you for finding this issue 😀 There is no reason at all. It is either a merge issue or me duplicating this line by mistake. It is corrected now.
